import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@styles/globals.css";
import Footer from "@/components/layout/footer";
import { GoogleTagManager, GoogleTagManagerNoScript } from "@/components/analytics/gtag";
import { AnalyticsProvider } from "../components/analytics/analytics-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <GoogleTagManager />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col overflow-x-clip`}
      >
        <GoogleTagManagerNoScript />
        <AnalyticsProvider>
          <div className="flex-1">{children}</div>
          <Footer />
        </AnalyticsProvider>
      </body>
    </html>
  );
}
